### PR TITLE
Created table for Resources

### LINKED ISSUE #1: enhancement: create a table for these resources
Resources to create a markdown table
- [Resource 1](https://www.tablesgenerator.com/markdown_tables): Table Generator - Very Helpful
- [Resource 2](https://github.com/kritanjalijain/Markdown_Cheatsheet#table) by a core team member.

### PR DESCRIPTION
**Pull request by mayurrkukreja**
Closes #1

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Thank you for opening a PR, @mayurrkukreja! Please remove the trailing forward slashes (`/`) from all the links.

**Comment by tusharnankani** [comment]
Hey @mayurrkukreja 
Thank you for the PR! :D

Do make the changes that Harsh asked.

What's your thought process behind `Resources / Miscellaneous`?

**Comment by mayurrkukreja** [comment]
> Thank you for opening a PR, @mayurrkukreja! Please remove the trailing forward slashes (`/`) from all the links.

Yes sure! I'll make the necessary changes create a pull request

**Comment by mayurrkukreja** [comment]
> Hey @mayurrkukreja Thank you for the PR! :D
> 
> Do make the changes that Harsh asked.
> 
> What's your thought process behind `Resources / Miscellaneous`?

I considered Resources / Miscellaneous section to be helpful specific to an opportunity mentioned.
As it would provide a curated list of the opportunities and the resources.

**Comment by mayurrkukreja** [comment]
Completed: Remove forward slashes `/` from table

**Review by tusharnankani — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
